---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check commit conventions

on:
  pull_request:
    branches:
      - "*"

jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # https://github.com/taskmedia/action-conventional-commits
      - uses: taskmedia/action-conventional-commits@e611e6d5471dc1853d7ab1642ed07c6abe28eb1d # v1.1.26
        with:
          types: "feat|fix|refactor|revert|ci|chore|docs|build|perf|test|style"
          skip_revert: false
